### ISSUE TITLE
Access Issues

### ISSUE THREAD

**Issue by HDVinnie** [Cclleemm/FriendlyTorrent#14]
Hello and thanks for this script. I have successfully installed this onto Ubuntu 16.04 (Xenial Xerus). I used the Automatic installation using the latest build via download link in readme. The install went fine and no errors occurred. All success! Now when I goto http://localhost/ all i see is the default Apache Page.

This is how I installed.

1) Downloaded Script
2) Opened Terminal
3) ran cd /Downloads/FriendlyTorrent-master
4) now that that is mounted I followed instructions for auto installer

5) sudo chmod +x ./install.sh

```
sudo ./install.sh (installed with no issues)

sudo nano /etc/apache2/apache2.conf   (made the respective changes said in readme)

sudo service apache2 restart
```

Then went to http://localhost/ and all i see is the default Apache Page.

Please Advise me on what i did wrong.....

**Comment by SCH94** [comment]
bro you need to change the default directory in sites-available
`sudo nano /etc/apache2/sites-available/000-default.conf`

and change the document root to /downloads/Friendlytorrent-master( or to the location of your FriendlyTorrent-master files)

then restart apache

**Comment by HDVinnie** [comment]
ok did that...conf reads as follows

```

<VirtualHost :*80>
        # The ServerName directive sets the request scheme, hostname and port t$
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /home/hdvinnie/Downloads/FriendlyTorrent-master

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
</VirtualHost>

```

saved it and restarted apache......still same Apache2 Ubuntu Default Page

please excuse my ignorance......I only so CSS, SASS, LESS, bootstrap, material design for living.

**Comment by SCH94** [comment]
bro are you on vps or you using your home computer.

**Comment by HDVinnie** [comment]
I am on my MacbookPro running VMWare Fushion with clean install of  Ubuntu 16.04 (Xenial Xerus)

**Comment by SCH94** [comment]
do you have static ip or dynamic ip

**Comment by HDVinnie** [comment]
Dynamic IP

**Comment by SCH94** [comment]
your configrations are not working correctly try this code

`sudo a2ensite 000-default.conf`

and restart apache

**Comment by HDVinnie** [comment]
hdvinnie@ubuntu:~$ sudo a2ensite 000-default.conf
[sudo] password for hdvinnie: 
Site 000-default already enabled
hdvinnie@ubuntu:~$ sudo service apache2 restart

If anything ill try it on a dedicated server running ubuntu if we cannot sort this

**Comment by SCH94** [comment]
in dedicated replace this  `VirtualHost :*80` with `VirtualHost : your_ip:80`

**Comment by HDVinnie** [comment]
didnt work....I dont want to be a pain....i can try on a dedicated server with static ip

**Comment by HDVinnie** [comment]
ok now when i enter my IP into browser it load and i see the friendly torrent.ico

but white page with following:

action = $action; $controller->setTitle(); call_user_func_array(array($controller,$action),$params); //$controller->$action(); $paramsString = ''; foreach($params as $key=>$value){ $paramsString .= '/'.$value; } //$core->bdd->sendReport($nameController.'/'.$action.$paramsString); } else{ echo '/!\ Error 404 /!\'; } ?>

**Comment by SCH94** [comment]
bro did you installed all the dependencies before initiating installation.

if you want to setup seedbox my suggestion would be that you go for rtorrent with rutorrent gui.

**Comment by HDVinnie** [comment]
Correct me if I'm wrong but doesn't the installer add the dependancies? 

I have a seedbox already. Running quickbox. But I am interested in checking this version out as well.

**Comment by clemh78** [comment]
Hello @HDVinnie ,

This software is outdated (we no longer maintain the code), so as @SCH94  said, we suggest you to use rtorrent with rutorrent gui or an another solution of seedbox.

Sorry :)

**Comment by HDVinnie** [comment]
very sad....it looks nice
