### ISSUE TITLE
Init

### ISSUE THREAD

**Issue by Shuunen** [Cclleemm/FriendlyTorrent#2]
Bonjour, 

Voici mon retour sur une install sur une debian 7 64bit fraiche :

- en tant que root sur debian, sudo n'est pas installé, j'ai donc du installer sudo pour éviter les erreurs de commande inconnue
- la réécriture du htaccess marche pas, je dois taper explicitement index.php?p=***
- les fichiers bdd.php et globals.php n'ont pu être créé via le script j'ai du le faire à la main

**Comment by Cclleemm** [comment]
Bonjour,
j'ai intégré l'installation de sudo si il n'est pas installé pour debian dans le dernier commit.
De plus, pour le HTACCESS j'ai ajouté dans le README quelques lignes expliquant comment l'activé.
Pour les fichiers de conf ça devrait marcher aussi.
