### ISSUE TITLE
Install.sh - MySQL: Command not found

### ISSUE THREAD

**Issue by Bitsnoxx** [Cclleemm/FriendlyTorrent#5]
Hey!
Bug?
MySQL database: Example
./install.sh: line 91: mysql: command not found
./install.sh: line 92: mysql: command not found
Can't import the database !

- Bitsnoxx

**Comment by Cclleemm** [comment]
Don,t Forget to restant your Apache service with : `sudo service apache2 restart`. I think is that for your 404 error.
