### ISSUE TITLE
English?

### ISSUE THREAD

**Issue by psycholyzern** [Cclleemm/FriendlyTorrent#8]
This is an interesting project. I set it up on my server, but how sad it is not English language.
You have any English version?

**Comment by Cclleemm** [comment]
Hello,
at the beginning, the project was just for us (french users), so the app is developed in french.
But I will translate it in english (maybe tooday), it's more comprehensible for everyone.

**Comment by psycholyzern** [comment]
I thought it will be in English as Readme is in English.
It will be great if you willing to do it today XD
No rush, take your time ;)

On August 20, 2015 7:40:36 PM GMT+08:00, "Clément Raussin" <notifications@github.com> wrote:
>Hello,
>at the beginning, the project was just for us (french users), so the
>app is developed in french.
>But I will translate it in english (maybe tooday), it's more
>comprehensible for everyone.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Cclleemm/FriendlyTorrent/issues/8#issuecomment-132983069

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Cclleemm** [comment]
Ok I will do that :)
If you find mistakes please help me to correct them beacause i'm not very good in english

**Comment by Cclleemm** [comment]
I just commit an english translation.
Does it work for you ?

Maybe i forget some tranlations, but most of words are translated.

I hope I don't add bugs ;)

Say me if I can close the issue.

**Comment by psycholyzern** [comment]
Nice! There are some not translated yet, but this is ok :)
I can help translate it on my free time (ofcourse using google translate XD).
Maybe you can make templates for languages for easier translation into another language in the future. 

Yes you can close this issu, but please take my suggestion into your consideration XD
And quota limit for eachniser would be great..

Thanks a lot for your hardwork!

**Comment by Cclleemm** [comment]
Yes, I didn't translate the "Charts".
I use simple constant page to translate the app : https://github.com/Cclleemm/FriendlyTorrent/tree/master/src/core/languages

If you want correct mistakes in the en.php you can update the project and do a pull request ;)

I added "Quota for users" in the TODO list : https://github.com/Cclleemm/FriendlyTorrent/wiki/TODO

Your welcome !
