### ISSUE TITLE
Erreur : vous avez été déconnecté

### ISSUE THREAD

**Issue by laouache** [Cclleemm/FriendlyTorrent#9]
Bonjour,

Je viens de lancer votre script d'installation sur UBUNTU 14.04 LTS server.
tout est ok jusqu'à l'ajout d'un torrent où j'ai le message d'erreur Erreur : vous avez été déconnecté.
j'ai vérifié les droits de /var/dowsnloads et dans le doute j'ai mis 777.

Dans quel cas ce message d'erreur apparait ?

**Comment by Cclleemm** [comment]
Bonjour,
en effet j'ai déjà rencontré ce bug, quel navigateur utilises tu ?

Essaye avec Chrome par exemple. Il me semble que c'est un problème avec le module d'upload que je n'ai pas encore corrigé...

**Comment by laouache** [comment]
Bonjour,

OK, ça marche avec Chrome mais j'ai encore une erreur : il reste bloqué sur Torrent non enregistré
![capture](https://cloud.githubusercontent.com/assets/12950619/9849196/cd4cd202-5ae8-11e5-866e-141544abef69.PNG)

Pourtant le service transmission est bien démarré.
Une idée ?

Pour infos, j'utilisais Firefox quand le bouton ajouter ne marchait pas.

**Comment by Cclleemm** [comment]
Ok, il faudrait vraiment corriger ce bug quand même si ça ne marche meme pas avec Firefox...
Pour le torrent non enregistré, je ne comprend pas, je laisse la main à @clemh78 pour te répondre.

**Comment by laouache** [comment]
Non laisse tomber, mon torrent de test était expiré.

Par contre puis je demander une évolution ? Il serait bien d'avoir quand même accès à transmission via le rpc avec login et mot de passe car l'application transmission remote est plutôt pratique si on veut renommer des fichiers/changer les répertoires des torrents (notamment pour PLEX), etc...

Seulement je ne peux pas modifier la configuration de transmission car apparemment vous la réécrasez à chaque fois.

Comment puis je faire ?

**Comment by laouache** [comment]
l'idéal serait de pouvoir modifier les options du service transmission afin de pouvoir personnaliser les process qui tourne pour utilisateur. rpc ou pas, limitation par ip ou pas...

**Comment by Cclleemm** [comment]
En effet c'est une bonne proposition. Mais actuellement le système d’interaction sur la configuration de transmission est un peu basique. Nous n'avons pas vraiment le temps actuellement de développer ça, mais si tu ajoutes quelques configs n'hésite pas à commit et on l'ajoutera au projet avec plaisir.
Avec PLEX tu peux faire pointer ton dossier de librairie sur le même répertoire que celui de FriendlyTorrent. Par contre c'est vrai que tu ne pourra avoir qu'une seule librairie...

J'ai ajouté ta proposition au TODO
